set(SOURCES
    core/byteio.cpp
    core/inputproc.cpp
    mapping/charset_components/charset_globals.cpp
    mapping/charset_components/charset_base.cpp
    mapping/charset_components/charset_unicode.cpp
    mapping/charset_components/charset_doublebyte.cpp
    mapping/charset_components/charset_viqr.cpp
    mapping/charset_components/charset_utf8_viqr.cpp
    mapping/charset_components/charset_library.cpp
    mapping/charset_components/charset_wincp1258.cpp
    mapping/charset_components/charset_stdvn.cpp
    mapping/macro_cache.cpp
    mapping/mactab.cpp
    mapping/text_macro_format.cpp
    tables/data.cpp
    tables/singlebyte/tcvn3.cpp
    tables/singlebyte/vps.cpp
    tables/singlebyte/viscii.cpp
    tables/singlebyte/bkhcm1.cpp
    tables/singlebyte/vietware_f.cpp
    tables/singlebyte/isc.cpp
    tables/doublebytes/vni_win.cpp
    tables/doublebytes/bkhcm2.cpp
    tables/doublebytes/vietware_x.cpp
    tables/doublebytes/vni_mac.cpp
    tables/error.cpp
    tables/usrkeymap.cpp
    patterns/pattern.cpp
    roof/convert.cpp
    engine/engine_components/table_components/table_globals.cpp
    engine/engine_components/table_components/table_vseq_cseq.cpp
    engine/engine_components/table_components/table_vcpair.cpp
    engine/engine_components/table_components/table_keyproc.cpp
    engine/engine_components/table_components/table_comparators.cpp
    engine/engine_components/table_components/table_validators.cpp
    engine/engine_components/table_components/table_init.cpp
    engine/engine_components/table_components/table_lookup.cpp
    engine/engine_components/diacritic_processing.cpp
    engine/engine_components/append.cpp
    engine/engine_components/process_io.cpp
    engine/engine_components/state.cpp
    engine/engine_components/macro.cpp
    engine/engine_components/restore.cpp
    engine/engine_components/setup.cpp
    engine/engine_components/word.cpp
    engine/unikey.cpp
)

add_library(ukengine STATIC ${SOURCES})

target_include_directories(ukengine
    PUBLIC
      $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/include>
      $<INSTALL_INTERFACE:include>
      ${CMAKE_CURRENT_SOURCE_DIR}/../include/ukengine
      ${CMAKE_CURRENT_SOURCE_DIR}/../include/ukengine/mapping
      ${CMAKE_CURRENT_SOURCE_DIR}/../include/ukengine/tables
      ${CMAKE_CURRENT_SOURCE_DIR}/../include/ukengine/patterns
      ${CMAKE_CURRENT_SOURCE_DIR}/../include/ukengine/roof
      ${CMAKE_CURRENT_SOURCE_DIR}/../include/ukengine/core
      ${CMAKE_CURRENT_SOURCE_DIR}/../include/ukengine/engine
      ${CMAKE_CURRENT_SOURCE_DIR}
      ${CMAKE_CURRENT_SOURCE_DIR}/engine
      ${CMAKE_CURRENT_SOURCE_DIR}/mapping
)

set_target_properties(ukengine PROPERTIES COMPILE_FLAGS "-funsigned-char -Wno-invalid-source-encoding -Wno-narrowing")

