// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Dumps each row of SingleByteTables (from tables/data.cpp) as comma-separated
 * 0xNN tokens to ukengine/tables/singlebyte/<name>.hex for later reuse.
 *
 * Run from the repository root (or pass the output directory as argv[1]):
 *   build/ukengine/dump_singlebyte_hex
 *   build/ukengine/dump_singlebyte_hex /path/to/ukengine/tables/singlebyte
 */
#include "mapping/charset.h"
#include "mapping/vnconv.h"

#include <cstdio>

int main(int argc, char **argv)
{
	const char *outDir = (argc > 1) ? argv[1] : "ukengine/tables/singlebyte";
	static const char *names[CONV_TOTAL_SINGLE_CHARSETS] = {
		"tcvn3", "vps", "viscii", "bkhcm1", "vietware_f", "isc"};

	for (int i = 0; i < CONV_TOTAL_SINGLE_CHARSETS; i++) {
		char path[1024];
		if (std::snprintf(path, sizeof(path), "%s/%s.hex", outDir, names[i]) >= (int)sizeof(path)) {
			std::fprintf(stderr, "output path too long\n");
			return 1;
		}

		FILE *f = std::fopen(path, "w");
		if (!f) {
			std::perror(path);
			return 1;
		}

		std::fprintf(f,
			"/* Row %d of SingleByteTables — %u bytes (TOTAL_VNCHARS). Same values as in ukengine/tables/data.cpp. */\n"
			"/* Generated by build target dump_singlebyte_hex; use as a C array initializer list. */\n",
			i, (unsigned)TOTAL_VNCHARS);

		for (int j = 0; j < TOTAL_VNCHARS; j++) {
			if (j) {
				std::fputc(',', f);
				if (j % 12 == 0)
					std::fprintf(f, "\n  ");
				else
					std::fputc(' ', f);
			} else
				std::fprintf(f, "  ");
			unsigned b = (unsigned)static_cast<unsigned char>(SingleByteTables[i][j]);
			std::fprintf(f, "0x%02x", b);
		}
		std::fputc('\n', f);
		std::fclose(f);
		std::printf("wrote %s\n", path);
	}
	return 0;
}
